# -*- coding: utf-8 -*-
"""CV_CO1_AT1_Q09

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hH7JOw_ah1tYE7vPmW-0JziY4iCT4dOV
"""

# ==========================================================
# Facial Recognition - Levels of Computer Vision
# Google Colab Compatible
# ==========================================================

import cv2
import numpy as np
import matplotlib.pyplot as plt

# ----------------------------------------------------------
# Step 1: Low-Level Computer Vision
# Create a synthetic face image
# ----------------------------------------------------------

img = np.zeros((300, 300), dtype=np.uint8)

# Face
cv2.circle(img, (150,150), 100, 200, -1)

# Eyes
cv2.circle(img, (115,120), 10, 0, -1)
cv2.circle(img, (185,120), 10, 0, -1)

# Mouth
cv2.ellipse(img, (150,185), (40,20), 0, 0, 180, 0, 3)

# Noise Reduction (Low-Level)
blur = cv2.GaussianBlur(img, (5,5), 0)

# Contrast Enhancement (Low-Level)
enhanced = cv2.equalizeHist(blur)

# ----------------------------------------------------------
# Step 2: Mid-Level Computer Vision
# Feature Extraction
# ----------------------------------------------------------

edges = cv2.Canny(enhanced, 100, 200)

# ----------------------------------------------------------
# Step 3: High-Level Computer Vision
# Simulated Face Recognition
# ----------------------------------------------------------

result = cv2.cvtColor(enhanced, cv2.COLOR_GRAY2RGB)

cv2.putText(result,
            "Face Recognized",
            (60,25),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (255,0,0),
            2)

# ----------------------------------------------------------
# Display Results
# ----------------------------------------------------------

plt.figure(figsize=(14,8))

plt.subplot(2,2,1)
plt.imshow(img, cmap='gray')
plt.title("Low-Level: Image Acquisition")
plt.axis("off")

plt.subplot(2,2,2)
plt.imshow(enhanced, cmap='gray')
plt.title("Low-Level: Enhanced Image")
plt.axis("off")

plt.subplot(2,2,3)
plt.imshow(edges, cmap='gray')
plt.title("Mid-Level: Feature Extraction")
plt.axis("off")

plt.subplot(2,2,4)
plt.imshow(result)
plt.title("High-Level: Face Recognition")
plt.axis("off")

plt.tight_layout()
plt.show()

# ----------------------------------------------------------
# Output
# ----------------------------------------------------------

print("Low-Level Computer Vision:")
print("- Image acquisition")
print("- Noise reduction using Gaussian Blur")
print("- Contrast enhancement using Histogram Equalization\n")

print("Mid-Level Computer Vision:")
print("- Feature extraction using Canny Edge Detection\n")

print("High-Level Computer Vision:")
print("- Simulated face recognition")
print("- Authentication decision: Face Recognized")
