# -*- coding: utf-8 -*-
"""CV-CO1-AT1-Q12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11g0fHJV579MGG9Uuhzcr9BVYekdY-_j9
"""

import cv2
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
print("Upload an image")
uploaded = files.upload()

filename = list(uploaded.keys())[0]

# Read image
img = cv2.imread(filename)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# ---------------------------------------
# Simulate Improper Image Formation
# (Blur + Low Contrast)
# ---------------------------------------

blurred = cv2.GaussianBlur(img, (11,11), 0)

low_contrast = cv2.convertScaleAbs(blurred, alpha=0.6, beta=0)

# ---------------------------------------
# Improve Image Formation
# ---------------------------------------

enhanced = cv2.convertScaleAbs(low_contrast, alpha=1.5, beta=20)

kernel = [[0,-1,0],
          [-1,5,-1],
          [0,-1,0]]

import numpy as np
kernel = np.array(kernel)

sharp = cv2.filter2D(enhanced, -1, kernel)

# ---------------------------------------
# Display Images
# ---------------------------------------

plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(img)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(low_contrast)
plt.title("Distorted Image")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(sharp)
plt.title("Improved Image")
plt.axis("off")

plt.show()

# ---------------------------------------
# Explanation
# ---------------------------------------

print("Possible Causes:")
print("- Lens distortion")
print("- Poor focus")
print("- Low lighting")
print("- Sensor noise")
print("- Motion blur")

print("\nCorrective Measures:")
print("- Camera calibration")
print("- Better lighting")
print("- Sharpening")
print("- Contrast enhancement")
print("- Noise reduction")
