# -*- coding: utf-8 -*-
"""CV_CO1_AT1_Q06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ngrSmVEYF9QJMLVB2Jt94Nbo9Jp9FJKz
"""

# ==========================================================
# Image Formation Model - Image Enhancement for Autonomous Driving
# Google Colab Compatible
# ==========================================================

# Install OpenCV (if not already installed)
!pip install opencv-python -q

# Import Libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# ==========================================================
# Step 1: Upload an Image
# ==========================================================
print("Upload a road image (jpg/png).")

uploaded = files.upload()

# Get uploaded filename
filename = list(uploaded.keys())[0]

# ==========================================================
# Step 2: Read Image
# ==========================================================
image = cv2.imread(filename)

if image is None:
    print("Error: Unable to load image.")
else:

    # Convert BGR to RGB
    original = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # ======================================================
    # Low-Level Image Formation Improvements
    # ======================================================

    # 1. Noise Reduction
    denoised = cv2.GaussianBlur(original, (5,5), 0)

    # 2. Contrast Enhancement
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    enhanced = cv2.equalizeHist(gray)

    # 3. Sharpening
    sharpening_kernel = np.array([
        [0,-1,0],
        [-1,5,-1],
        [0,-1,0]
    ])

    sharpened = cv2.filter2D(original, -1, sharpening_kernel)

    # 4. Edge Detection
    edges = cv2.Canny(enhanced, 100, 200)

    # ======================================================
    # Display Results
    # ======================================================

    plt.figure(figsize=(15,10))

    plt.subplot(2,3,1)
    plt.imshow(original)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(2,3,2)
    plt.imshow(denoised)
    plt.title("Noise Reduction")
    plt.axis("off")

    plt.subplot(2,3,3)
    plt.imshow(enhanced, cmap='gray')
    plt.title("Contrast Enhancement")
    plt.axis("off")

    plt.subplot(2,3,4)
    plt.imshow(sharpened)
    plt.title("Sharpened Image")
    plt.axis("off")

    plt.subplot(2,3,5)
    plt.imshow(edges, cmap='gray')
    plt.title("Edge Detection")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

    # ======================================================
    # Summary
    # ======================================================
    print("\nImage Formation Model Improvements:")
    print("✓ Noise Reduction using Gaussian Blur")
    print("✓ Contrast Enhancement using Histogram Equalization")
    print("✓ Image Sharpening using Convolution Filter")
    print("✓ Edge Detection using Canny Operator")
    print("\nThese preprocessing steps improve image quality for autonomous driving applications such as lane detection, vehicle detection, and obstacle recognition.")
